[awakened-poe-trade]
src.github_tag = "SnosMe/awakened-poe-trade"
src.prefix = "v"
fetch.url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v$ver/Awakened-PoE-Trade-$ver.AppImage"

[exiled-exchange-2]
src.github_tag = "Kvan7/Exiled-Exchange-2"
src.prefix = "v"
fetch.url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v$ver/Exiled-Exchange-2-$ver.AppImage"

[rusty-path-of-building]
src.github_tag = "meehl/rusty-path-of-building"
fetch.github = "meehl/rusty-path-of-building"

[vivid-plasma-themes]
src.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"

[niri]
src.git = "https://github.com/YaLTeR/niri"
fetch.github = "YaLTeR/niri"
